### PR TITLE
Fix some small bugs in gymnasium.vector

### PR DESCRIPTION
**Pull request by xihuai18**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

- Avoid unnecessary reset in sync_vector_env.py
- Fix some typos and type hints in async_vector_env.py

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Please could you explain the PR, I don't understand the change

**Comment by xihuai18** [comment]
I think `self._autoreset_envs` records whether the sub-environments should be reset in the next step. However, after the `reset` method of SyncVectorEnv instances is manually called, `self._autoreset_envs` is not set to all `False`, leading to some sub-environments will be *reset twice* consecutively.

I also noticed that in `_aysnc_worker` of `async-vector_env.py`, the `autoreset` flag is set to `False` if the `reset` method is manually called.

So I think `self._autoreset_envs` should be set to all `False` at the end of the `reset` method of SyncVectorEnv.

If I am wrong, ignore this PR.

**Comment by xihuai18** [comment]
In addition, there may be some typos in `_async_worker` of `async_vector_env.py` and I fix them.

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
Could you add a test for these features to show them as an issue

**Comment by pseudo-rnd-thoughts** [comment]
@xihuai18 Your correct about the autoreset for `SyncVectorEnv` however the other two changes I don't believe are correct. 
Could you revert those changes then it should be good to merge

**Comment by xihuai18** [comment]
I'd like to explain my changes:
1. exceptions for `_call`
https://github.com/Farama-Foundation/Gymnasium/blob/1878f6dd7d69439dc770289a9000eed6a52b4a43/gymnasium/vector/async_vector_env.py#L700-L726

Line 725 shows that all accepted commands are `reset`, `step`, `close`, `_call`, `_setattr`, `_check_spaces`, so corresponding exceptions are changed in Line 702. For example, one can not `_call` `_setattr`, but should use the `_setattr` method directly.

2. type hints for `shared_memory`
https://github.com/Farama-Foundation/Gymnasium/blob/1878f6dd7d69439dc770289a9000eed6a52b4a43/gymnasium/vector/async_vector_env.py#L669-L672

`shared_memory` are used for writing in the obtained obserations via `write_to_shared_memory` function (if it is not `None`). Thus it should be a `multiprocessing.Array` or other nested types, as defined in https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/vector/utils/shared_memory.py.

**Comment by xihuai18** [comment]
I have passed the pre-commit now.

**Comment by pseudo-rnd-thoughts** [comment]
Ahh you are right on `shared_memory`, I had missed the line below and thought it must have been a boolean

For the error, it is around the function / attr being called not the command. The list you have updated is the list of commands but not if the function should be called. 
Saying that, I think the list should be `"reset", "step", "close"` and with `"set_wrapper_attr"` users should just use `"set_attr"` the error doesn't support a different function name.

**Comment by xihuai18** [comment]
> Ahh you are right on `shared_memory`, I had missed the line below and thought it must have been a boolean
> 
> For the error, it is for the function / attr name not the command, i.e., `envs.call("reset")` is disabled. The list you have updated is the list of commands but not if the function should be called. Saying that, I think the list should be `"reset", "step", "close"` and with `"set_wrapper_attr"` users should just use `"set_attr"` the error doesn't support a different function name.

I think the current version is right according to your review?

**Review by pseudo-rnd-thoughts — APPROVED** [review]

**Pull request merged**
