### PR TITLE
Updated Wrapper docs

### PR DESCRIPTION
**Pull request by Markus28**
- Some descriptions of what wrappers do was moved from doctoring of superclass to module docstring
- Examples of wrapper implementations were moved from docstrings to a tutorial
- Removed the titles for each individual wrapper in the docs

### CODE REVIEW

**Review by pseudo-rnd-thoughts — APPROVED** [review]
Are there any links between the tutorials and api docs

**Comment by Markus28** [comment]
Not yet, but I can add one from the tutorial to the docs :)
Should we also do one from the module doctoring to the tutorial? That would need to be an absolute URL then, right?

**Comment by pseudo-rnd-thoughts** [comment]
I believe that sphinx allows both relative and absolution links

**Comment by Markus28** [comment]
Done :)

**Pull request merged**
