### PR TITLE
Formatting error in create_custom_env.md

### PR DESCRIPTION
**Pull request by carschandler**
Title

## Type of change

Please delete options that are not relevant.

- [x] Documentation only change (no code changed)

### CODE REVIEW

**Comment by Kallinteris-Andreas** [comment]
for reference, this is how it is currently rendered
image
@carschandler can you provide a screenshot of how your need version is rendered
thanks

**Comment by carschandler** [comment]
@Kallinteris-Andreas sure, is there a deployment that gets created by the actions somewhere that I can use to screenshot?

**Comment by Kallinteris-Andreas** [comment]
No idea i just compile the website locally

**Comment by carschandler** [comment]
Screenshot 2024-11-11 at 8 41 15 PM

**Review by Kallinteris-Andreas — APPROVED** [review]

**Pull request merged**
