### PR TITLE
remove requirement of mujoco envs defining `metadata["render_fps"]`

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
For backwards compatibility we keep the old method for asserting `render_fps`.
When `render_fps` is not defined let it be auto defined
useful when using custom `frame_skip` or `xml_file`

### CODE REVIEW

**Comment by mhboool** [comment]
> 

jawaker

**Comment by pseudo-rnd-thoughts** [comment]
Could you add a test to vary the frame-skip value?

**Comment by Kallinteris-Andreas** [comment]
`v4` does not have a `frame_skip` arg, but `v5` does (and potentially 3rd party environments that inherit `MujocoEnv`)

I am using this locally for `v5` 
```py
@pytest.mark.parametrize("env", ['Ant', 'HalfCheetah', 'Hopper', 'Humanoid', 'HumanoidStandup','InvertedDoublePendulum', 'InvertedPendulum', "Pusher", "Reacher", "Swimmer", 'Walker2d'])
@pytest.mark.parametrize("version", ['v5'])
@pytest.mark.parametrize("frame_skip", [1, 2, 3, 4, 5])
def test_frame_skip(env, version, frame_skip):
    """verify that all `mujoco` envs work with different `frame_skip` values"""
    env_id = f"{env}-{version}"
    env = gym.make(env_id, frame_skip=frame_skip)

    # Test if env adheres to Gym API
    with warnings.catch_warnings(record=True) as w:
        gym.utils.env_checker.check_env(env.unwrapped, skip_render_check=True)
        env.close()
    for warning in w:
        if warning.message.args[0] not in CHECK_ENV_IGNORE_WARNINGS:
            raise Error(f"Unexpected warning: {warning.message}")

```

**Comment by pseudo-rnd-thoughts** [comment]
Ahh, I see now. That test looks good.
Could you add a test in gymnasium still with a custom mujoco environment to test that the metadata and frame skips don't cause issues?

**Comment by Kallinteris-Andreas** [comment]
I have added a test https://github.com/Kallinteris-Andreas/Gymnasium-kalli/blob/patch-20/tests/envs/test_mujoco_custom_env.py

**Review by pseudo-rnd-thoughts — APPROVED** [review]

**Pull request merged**
