### PR TITLE
Update env_checker.py

### PR DESCRIPTION
**Pull request by chrisyeh96**
Fix typo about Box maximum limit. Add return type annotations.

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for spotting that, could you fix the tests. You should just need to update the `IGNORE_WARNINGS` list to include the new case

**Comment by chrisyeh96** [comment]
@pseudo-rnd-thoughts: I have updated the `CHECK_ENV_IGNORE_WARNINGS` list

**Comment by chrisyeh96** [comment]
Updated the `CHECK_ENV_IGNORE_WARNINGS` in two more test files. This should fix the failing tests.

**Review by pseudo-rnd-thoughts — APPROVED** [review]
Amazing, thanks for the changes

**Pull request merged**
