### PR TITLE
Update frozen_lake.py

### PR DESCRIPTION
**Pull request by Yanipo5**
# Description

Set max_episode_steps as 200 for 8x8 maps (currently 100 steps)

Fixes # (issue)

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Screenshots

image

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Hey, why do you make this change? 
If users want to they can change the number of time steps for an environment with `gym.make("FrozenLake", max_episode_steps=200)`?

**Comment by Yanipo5** [comment]
@pseudo-rnd-thoughts 
> Hey, why do you make this change? If users want to they can change the number of time steps for an environment with `gym.make("FrozenLake", max_episode_steps=200)`?

Cause the 8x8 => 200 is part of the specs,
Therefore it should be the default, no so?

> Episode End
> ...
> The length of the episode is 100 for 4x4 environment, 200 for 8x8 environment.

**Comment by RedTachyon** [comment]
This is more of a documentation issue, as the two versions of the environment registered by default use 100 and 200 steps, for 4x4 and 8x8 respectively. For custom scenarios, people are free to set their own time limit.

https://github.com/Farama-Foundation/Gymnasium/blob/01308340aec7dd487c714e627d9f248eb646541b/gymnasium/envs/__init__.py#L136-L150

It might be useful to change the wording in the documentation to be a bit clearer, but I don't think this warrants a code change.

**Comment by pseudo-rnd-thoughts** [comment]
Ahh, apologies. 

`FrozenLake8x8-v1` exists as the implementation of 8x8 and has `max_episode_steps=200` already so this PR is not necessary.  
 https://github.com/Farama-Foundation/Gymnasium/blob/01308340aec7dd487c714e627d9f248eb646541b/gymnasium/envs/__init__.py#L144

However, reading the documentation for [frozen lake](https://gymnasium.farama.org/environments/toy_text/frozen_lake/) so we need to fix this. Would you mind updating the documentation on [line](https://github.com/Farama-Foundation/Gymnasium/blob/01308340aec7dd487c714e627d9f248eb646541b/gymnasium/envs/toy_text/frozen_lake.py#L84) to include details about the 8x8 version

**Comment by Yanipo5** [comment]
OK, I'll update the docs.
Though I have to say, my experience was that I didn't know about the 8x8 env variant, and I used "FrozenLike-v1" with desc="8x8".
Therefore I assumed it was playing 200 steps, which I was "surprised to learn was actually 100. 

Well maybe it's fine if we make it explicit in the docs.

**Pull request closed without merging**
