### PR TITLE
fix `load_quadruped_model` tutorial not being listed

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
fixes https://github.com/Farama-Foundation/Gymnasium/issues/901

credit: @mgoulao

### CODE REVIEW

**Review by pseudo-rnd-thoughts — APPROVED** [review]

**Comment by Kallinteris-Andreas** [comment]
I can not build the docs locally, so I can not confirm if the fix works
please do a 
```sh
git clone git@github.com:Farama-Foundation/Gymnasium.git
cd Gymnasium
git checkout Kallinteris-Andreas-patch-3
cd docs
make dirhtml 
```


> (or I could the lazy thing of merge it, let it auto deploy the docs, and then revert if it does not work)

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
Ahh, I have tested and this doesn't work
@mgoulao any ideas?

**Comment by Kallinteris-Andreas** [comment]
@mgoulao can you take a look

**Comment by mgoulao** [comment]
Ok, so got it working by adding the file to a different toctree directive, also it is necessary to tell sphinx-gallery to copy  `.md` files. The diff with changes needed is below:
```
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -130,6 +130,7 @@ sphinx_gallery_conf = {
     "ignore_pattern": r"__init__\.py",
     "examples_dirs": "./tutorials",
     "gallery_dirs": "./tutorials",
+    "copyfile_regex": r"./tutorials/.*\.md",
     "show_signature": False,
     "show_memory": False,
     "min_reported_time": float("inf"),
diff --git a/docs/index.md b/docs/index.md
index 356372f8..20853586 100644
--- a/docs/index.md
+++ b/docs/index.md
@@ -86,7 +86,6 @@ environments/third_party_environments
 :caption: Tutorials

 tutorials/**/index
-tutorials/**/*.md
 tutorials/third-party-tutorials
 Comet Tutorial <https://www.comet.com/docs/v2/integrations/ml-frameworks/gymnasium/?utm_source=gymnasium&utm_medium=partner&utm_campaign=partner_gymnasium_2023&utm_content=docs_gymnasium>

diff --git a/docs/tutorials/gymnasium_basics/README.rst b/docs/tutorials/gymnasium_basics/README.rst
index 29c32e7b..c11f273c 100644
--- a/docs/tutorials/gymnasium_basics/README.rst
+++ b/docs/tutorials/gymnasium_basics/README.rst
@@ -1,2 +1,7 @@
-Gymnasium Basics
-----------------
+Gymnasium Basics^M
+----------------^M
+^M
+.. toctree::^M
+   :hidden:^M
+^M
+   /tutorials/gymnasium_basics/load_quadruped_model.md^M
 ```

**Comment by Kallinteris-Andreas** [comment]
@mgoulao can you make a PR?

**Comment by mgoulao** [comment]
Yes, do you want a PR to your branch or main?

**Comment by Kallinteris-Andreas** [comment]
preferably main, but i do not really care

**Pull request closed without merging**
