### PR TITLE
HumanVectorRendering: based on VectorWrapper (#873, #872, #233)

### LINKED ISSUE #872: [Bug Report] Various rendering issues in 'cartpole.py'
### Describe the bug

1. Accepts any string as 'render_mode' then assumes everything else than 'human' to be "rgb_array"
2. line 512-513: test that 'self.clocks' is None, then sets 'self.clock'...
3. line 525-526: transposes x but does not pick the to the environment corresponding data

### Code example

```shell
__init__


        if self.clocks is None:
            self.clock = [pygame.time.Clock() for _ in range(self.num_envs)]

        for state, screen, clock in zip(self.state, self.screens, self.clocks):
            x = self.state.T
```

### System info

Gymnasium installed from source
version 1.0.0rc1
Windows
Python 3.11

### Additional context

Issues corrected in the HumanVectorRenderingPR4

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

### LINKED ISSUE #873: [Proposal] Vector environments can not currently be rendered
### Proposal

Add rendering for vector environments

rgb_array:
environment should be able to choose to return a single frame (itself selecting what parallel environment to render) or a list of frames

rgb_array_list:
environment should return a list of list of 'rgb_array' output

### Motivation

I need it for my project!

### Pitch

_No response_

### Alternatives

Add native rendering in every vector project

### Additional context

HumanVectorRenderingPR5 implements this, related issue #233

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

### PR DESCRIPTION
**Pull request by RogerJL**
Corrected code to pass tests, and tests to test code! Also corrected some bugs in vectorized Cartpole #872 
Doctest: fixed comments

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #872
Fixes #873 
Related to #233 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

| Before | After |
| ------ | ----- |
| N/A | HumanVectorRender|

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by RogerJL** [comment]
@pseudo-rnd-thoughts @Kallinteris-Andreas please review

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
I haven't looked at the code in detail but vector wrappers should go in wrappers.vector so could you move the code (including test) to the wrapper vector folders. You will need to create new folders possibly.
Also I wouldn't worry about changing the vector cart pole implementation

**Comment by RogerJL** [comment]
HumanRenderer and HumanVectorRenderer has a common base class to avoid code duplication. Splitting them might be complicated - but doable. Could split them but then I think the base class ends up in vector or it must be placed in some utility directory. I am not sure this is better...

Fixes in Vector Cartpole are required to make test (and code examples) work.

**Comment by pseudo-rnd-thoughts** [comment]
You can share code but normal wrappers go in "wrappers" and vector wrappers in "wrappers.vector" and so don't include vector in front of their name so are called the same name as their equivalent normal wrapper.
This is to allow easy changes in code between normal and vector with minimal name changes

**Pull request closed without merging**
