### PR TITLE
refactor(hopper_v4): add forward/health reward and ctrl cost to step info

### PR DESCRIPTION
**Pull request by rickstaa**
# Description

This pull request adds the Forward and Health reward and control cost to the `info` dictionary that is returned by the `step` method of the `hopper_v4` environment.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas Do we want to add the info ideas to v4 as well?

**Comment by Kallinteris-Andreas** [comment]
i would rather not change the functionality of `v4`

**Comment by pseudo-rnd-thoughts** [comment]
@rickstaa Thanks for the PR but we are going to keep v4 as it is, we are hopefully releasing mujoco v5 environments that will include these changes

**Comment by rickstaa** [comment]
> @rickstaa Thanks for the PR but we are going to keep v4 as it is, we are hopefully releasing mujoco v5 environments that will include these changes

No problem I was not aware of https://github.com/Farama-Foundation/Gymnasium/pull/572. Thanks!

**Pull request closed without merging**
