### PR TITLE
forzen lake Truncation doc

### PR DESCRIPTION
**Pull request by Yanipo5**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] This change requires a documentation update

### CODE REVIEW

**Comment by Kallinteris-Andreas** [comment]
1) do not change the `.gitignore`
2) what is the benefit of the change? You are likely to create confusion on how to use `make`.

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas There is a large issue that the FrozenLake documentation doesn't note the existence of the `FrozenLake8x8` so we need to do a larger rewrite of the documentation. 
Additionally, I was worried that similar issues existed for other environments but in checking, I can't find another issue

**Comment by Yanipo5** [comment]
>what is the benefit of the change? You are likely to create confusion on how to use make.
I think it is currently confusing. @Kallinteris-Andreas 

My experience was that I thought that by selecting the "8X8" map, I was granted 200 steps.
I had to debug the running environment to discover I actually had 100 steps on a 8X8 map.

My suggestion is either change the default to be if n_row > 3 ==> steps = 200 (#458)
Or specify that this requires the `FrozenLake8x8-v1`
Else, it is already confusing...

So what's the verdict here?

**Comment by Kallinteris-Andreas** [comment]
as sorry got confused,
LTGT, besides the edit to `.gitignore`

**Comment by Yanipo5** [comment]
Call I'll remove the .gitignore

**Review by pseudo-rnd-thoughts — APPROVED** [review]

**Pull request merged**
