### PR TITLE
Fix Lunar Lander termination criteria

### PR DESCRIPTION
**Pull request by jjshoots**
# Description

This fixes lunar lander termination criteria.

Fixes [this](https://github.com/Farama-Foundation/Gymnasium/issues/377#issuecomment-1655610667)

### CODE REVIEW

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
Without a version change we can't do this therefore I would preemptively reject this PR

To my knowledge, all the issue requires changing is the bound

**Comment by jjshoots** [comment]
@pseudo-rnd-thoughts I'm not sure if that's an ideal thing to do. As it stands the environment doesn't check for when the lander goes out of the map in the y direction, only x. So in theory, the lander could be y = 1000 and the environment would still be valid as long as x is in [-1, 1]. If we change the bounds, what it should be is kind of weird since no matter what number we give it, there will always be a valid y value outside of that.

The change I made simply makes it so that the environment additionally checks the y coordinate. I agree that this requires a version bump though.

**Comment by pseudo-rnd-thoughts** [comment]
I agree that it doesn't make much sense in terms of visualisation currently but this doesn't break the environment specification as it is currently. To me, the cost of version bumping to benefit of adding this is too much

Therefore, I would set the y bound to something quite high, 1000 which is difficult to achieve

**Comment by jjshoots** [comment]
That's fair, I'll modify the bounds then. Although I should mention that in some instances, the observation space bounds are used for normalisation of the observation itself, so this may result in previously trained models performing differently. Although, agreed that just changing the bounds is a less disruptive change.

**Comment by pseudo-rnd-thoughts** [comment]
We have modified the observation two or three times over the last few versions (which we should note somewhere)

**Pull request closed without merging**
