### PR TITLE
Replace homepage video with GIF, revert text/formatting changes

### PR DESCRIPTION
**Pull request by elliottower**
# Description

This PR updates the video which was added in #426 to be a GIF, so it autoplays on iOS devices. It also does some other changes to make the homepage consistent with other Farama projects and with the previous homepage. Screenshots below of before/after.

For example, the title was changed to be centered rather than left aligned, and used the deprecated html `<center>` tag, and made Gymnasium's website inconsistent with other Farama sites. Changes like that should be done across the board to ensure branding/imaging is consistent. 

The text changes were not bad per-se, but the rephrasing removed an important part, how Gymansium is "capable of representing general RL problems". This bit is much more important IMO than saying you can create your own environment, as a researcher reading it will be much more interested in the theoretical limitations, rather than ease of use for creating a new environment. I felt it wasn't necessary to say 'execute the action in the environment' either, as `env.step(action)` is so dead simple, and the comment distracts from the policy comment.
* We can add a bit about creating new custom environments easily/having tutorials for it as well if we want

The bit mentioning that models were trained using SB3 and linking to the huggingface SB3 leaderboard I didn't think was necessary, but can be added back if we want (and should probably use rst/sphinx captions rather than HTML tags)
___ 

It looks like I'm removing a lot of information but this is the homepage (where people go for five seconds and want to be able to easily get all the important info) and all the other Farama sites have very simple homepages with just the title, basic headline, and code example. The big block of un-bolded text in the previous PR is a bit hard to skim and repeats some information from the title.

A separate PR should be made IMO for actual text content changes, I'm just going back to V28.1's text. 

Previous homepage (from #426) 
Screen Shot 2023-04-26 at 2 30 29 PM

Homepage with my PR (note the screenshot is towards the end of the gif, the first env it shows off is walker2d)
Screen Shot 2023-04-26 at 2 34 51 PM

Current V28.1 homepage (pretty much the exact same as my PR but with only lunar lander video, rather than the envs demo)
Screen Shot 2023-04-26 at 2 40 09 PM

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by araffin** [comment]
> The bit mentioning that models were trained using SB3 and linking to the huggingface SB3 leaderboard I didn't think was necessary, but can be added back if we want (and should probably use rst/sphinx captions rather than HTML tags)

@till2 asked me for permission to re-use the videos, I agreed, but crediting SB3 was the condition.

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
@araffin Thanks for spotting that, @elliottower could you revert the change.

Also, could we implement the suggested changes we discussed on discord?

**Comment by elliottower** [comment]
Makes sense, sorry about removing it.

**Comment by RedTachyon** [comment]
Closing this in favor of #476. If we want to edit the writing and stuff like that, let's do it in a new PR

**Pull request closed without merging**
