### PR TITLE
update pyright to 1.1.383

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
@Kallinteris-Andreas `213 errors, 6 warnings, 0 informations` ooof

**Comment by Kallinteris-Andreas** [comment]
Some of the errors are straight up wrong (unless I am crazy)
```sh
 /home/runner/work/Gymnasium/Gymnasium/gymnasium/envs/mujoco/reacher_v4.py
  /home/runner/work/Gymnasium/Gymnasium/gymnasium/envs/mujoco/reacher_v4.py:29:35 - error: Argument of type "dict[str, int]" cannot be assigned to parameter "default_camera_config" of type "Dict[str, float | int] | None" in function "__init__"
    Type "dict[str, int]" is not assignable to type "Dict[str, float | int] | None"
      "dict[str, int]" is not assignable to "Dict[str, float | int]"
        Type parameter "_VT@dict" is invariant, but "int" is not the same as "float | int"
        Consider switching from "dict" to "Mapping" which is covariant in the value type
      "dict[str, int]" is not assignable to "None" (reportArgumentType)
```
`int` should be assignable to `float | int`

I am strictly opposed to moving to `MyPY`, but it likely require all the other Farama projects to change to `MyPy also`

**Comment by Kallinteris-Andreas** [comment]
note: I have edited my previous message by adding a "not", misstyping sorry

**Comment by Kallinteris-Andreas** [comment]
I have disabled `reportAttributeAccessIssue`, `reportArgumentType` as I think they create wrong issues


I have temporarily disabled the following, which can be fixed one at a time
`reportIndexIssue`, `reportReturnType`, `reportCallIssue`, `reportOperatorIssue`, `reportInvalidTypeForm`, `reportOptionalMemberAccess`, `reportRedeclaration`, `reportAssignmentType`

**Review by pseudo-rnd-thoughts — APPROVED** [review]
My only worry with this update is that it doesn't actually fix any of the type problems, just hides them better. 

An alternative approach is to use something like https://github.com/beartype/beartype which operates during testing to check that the types passed to functions match the exacted type. Quite cool imo

**Pull request merged**
