### PR TITLE
pin `mujoco <= 3.1.1`

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
I will work with the mujoco devs tomorrow to fix the bug, for now this should work

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Are we sure this isn't a bug within MuJoCo?

**Comment by RogerJL** [comment]
Is the below build error caused by this problem?

[Failed build](https://github.com/RogerJL/Gymnasium/actions/runs/7806176036/job/21291981482
)

**Comment by Kallinteris-Andreas** [comment]
@RogerJL yes, you may ignore it

**Review by pseudo-rnd-thoughts — APPROVED** [review]
Merging as a immediate patch

**Pull request merged**
