### PR TITLE
Fix `MuJoCo.Humanoid` action description

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
# Description

The old description appears to have been a copy and paste of `MuJoCo.Ant` description

### CODE REVIEW

**Comment by Kallinteris-Andreas** [comment]
Sources:
https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/assets/humanoid.xml#L103
https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/mujoco/assets/humanoidstandup.xml#L103

**Review by pseudo-rnd-thoughts — APPROVED** [review]
Thanks, sorry for taking so long to approve
Could you fix the pre-commit,`pip install pre-commit` `pre-commit run --all-files`

**Comment by Kallinteris-Andreas** [comment]
`pre-commit` does nothing for me 
(also note the files, that fail the `pre-commit` on GitHub workflow are unrelated to my PR)

**Comment by pseudo-rnd-thoughts** [comment]
Ok, you need to update your fork and merge with main.

**Comment by Kallinteris-Andreas** [comment]
Ok, pc passes now

**Pull request merged**
