### PR TITLE
refactor: EzPickle -> @ezpickle :recycle:

### PR DESCRIPTION
**Pull request by robertoschiavone**
# Description

This commit changes EzPickle from being a class to being a decorator.

The edits are only internal, they don't change or break the existing APIs.

Pros:

- Removed every instance of multiple inherintance in the codebase.
- Automated serialization of constructor arguments, no need to manually copy/paste them and keep track of them in case the constructor changes.
- I discovered at least one instance of useless arguments, where such argument is only serialized and then never used anymore (`default_camera_config` in `ant_v5.py`).

Cons:

- none that I can think of
  
## Type of change

- [x] Refactor

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by RedTachyon** [comment]
Worth noting that this absolutely is a breaking change, since 3rd-party envs can use `EzPickle` to keep consistency with internal gymnasium envs, since `EzPickle` is explicitly an exported class from its module.

In principle I'm not opposed to removing multiple inheritance, but we need to be very careful about this. At the very least we'd probably need to keep `EzPickle` (the class) around for a long time. The only point where I can see it being removable is for 1.0, but even then I'm not sure if it's worth the hassle. 

Even if we keep `EzPickle`, that doesn't mean we can't convert internal code to something better, but I'm not sure if a decorator applied to the constructor is the right way to go, I haven't seen a pattern like this... ever, probably for a good reason. Modifying the class methods inside of it is even more opaque.

With all my distaste for multiple inheritance, in this case it might not be the worst thing, since all it should do is just record some things and then pass the arguments on to the next parent class. But as I said, if there's a solution that's significantly less cursed (as a ratio to how breaking of a change it is)

**Review by RedTachyon — CHANGES_REQUESTED** [review]
Just marking the review to avoid an accidental merge

**Comment by Kallinteris-Andreas** [comment]
Even if `@ezpickle` is added, `EzPickle` should be kept for backwards compatibility with a deprecation warning

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
While I agree that this is a relatively elegant solution and prevents the needs for listing all of the arguments. 
I think there is another issue not mentioned is the type checking, I might be wrong but if you initialise an Env, the environment type is not `Env` but an `ezpickle` function

**Comment by pseudo-rnd-thoughts** [comment]
Due to the issue I list above, unless the issue doesn't exist or we can find a solution, I'm going to close the issue

**Pull request closed without merging**
