### PR TITLE
Use poetry to do package management

### PR DESCRIPTION
**Pull request by vwxyzjn**
This PR uses poetry as the package manager. 

The legacy `setup.py` is removed in favor of the new `pyproject.yaml`. (`setup.py` is getting deprecated — see https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/)

### CODE REVIEW

**Comment by RedTachyon** [comment]
Does this make poetry required to use gym? Or will people still be able to just do `pip install -e .`/`pip install gym` in a regular venv and use it normally?

**Comment by vwxyzjn** [comment]
> Does this make poetry required to use gymnasium? Or will people still be able to just do pip install -e ./pip install gymnasium in a regular venv and use it normally?

Yes. 

Note that there is no way to specify `box2d-py` as a dependency. 

Poetry by default uses PEP 517 to install and build dependencies, but `box2d-py` breaks (e.g., try `pip install box2d-py --use-pep517` which will break).  We can not specify `box2d-py` needs to be installed by using non pep 517 in poetry (see https://github.com/python-poetry/poetry/issues/3433), so I currently set to install `box2d-py` manually via

```Dockerfile
RUN poetry run pip install swig==4.0.2
RUN poetry run pip install --no-use-pep517 box2d-py==2.3.8
```

**Comment by Dmusulas** [comment]
Merging this PR would also accept and solve this issue https://github.com/Farama-Foundation/Gymnasium/issues/7

**Comment by kir0ul** [comment]
I'd also remove `requirements.txt` and `test_requirements.txt`, see https://github.com/Farama-Foundation/Gymnasium/issues/7#issuecomment-1252574113.

**Comment by pseudo-rnd-thoughts** [comment]
Could @vwxyzjn or @RedTachyon write a summary of the offline discussion about Poetry. I believe while adding poetry would be a good thing to add, there are several current issues that limit us from doing that

**Pull request closed without merging**
