### PR TITLE
add tests for blackjack edge cases

### LINKED ISSUE #1011: [Bug Report] Calculating rewards for Blackjack toy-text env
### Describe the bug

In blackjack.py: reward = cmp(score(self.player), score(self.dealer))

Current rewards seem wrong for 2 edge cases: 

1. Player: Blackjack vs Dealer: 21. Currently this return a draw (reward = 0) while it should be 1 (b/c player wins). 
2. Player and dealer both bust: Currently this return a draw (reward = 0) while it should be -1 (dealer wins). 

### Code example

```shell
In blackjack.py: 
Inside function step():
reward = cmp(score(self.player), score(self.dealer))

And definition of score() and cmp(): 
def score(hand):  # What is the score of this hand (0 if bust)
    return 0 if is_bust(hand) else sum_hand(hand)
def cmp(a, b):
    return float(a > b) - float(a < b)
```

### System info

- Gymnasium, main branch 
- Python 3.9

### Additional context

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

### PR DESCRIPTION
**Pull request by CloseChoice**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Not sure if we really need these additional tests for the blackjack environment but since these cases where explicitly discussed in the linked issue I think there is no harm in adding them and making the behaviour in these cases explicit.

Fixes #1011 (issue)

## Type of change
adding tests for the discussed cases.

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
FYI, the errors are all due to NumPy 2 release, we are in the process of making a PR to fix it

**Comment by CloseChoice** [comment]
> FYI, the errors are all due to NumPy 2 release, we are in the process of making a PR to fix it

I could also restrict the numpy version to "<2" in this PR

**Comment by CloseChoice** [comment]
@pseudo-rnd-thoughts : Sorry for the delay, somehow overlooked the notification of your reaction. I updated the pyproject.toml file, we can give this a try

**Comment by CloseChoice** [comment]
@pseudo-rnd-thoughts : is someone working on numpy 2 support? I took a look (at a couple of the issues) and can create draft a PR if nobody actively works on this.

**Comment by pseudo-rnd-thoughts** [comment]
@CloseChoice Sorry for taking a while, we have updated the project to work with numpy 2.0

Looking at the PR, I'm a bit confused at what the PR is doing. It just adds a test meaning that there is no issue with the implementation. Therefore, do we need the test? And can we close the related issue

**Comment by CloseChoice** [comment]
Thanks for coming back to this. I mentioned in the related issue that IMO the implementation is not a problem and there are either special rules (while the standard ones are implemented) and added tests for the standard rules that weren't covered yet, but mentioned in the issue. Also in the PR description I mentioned that we might not need this PR at all:

> Not sure if we really need these additional tests for the blackjack environment but since these cases where explicitly discussed in the linked issue I think there is no harm in adding them and making the behaviour in these cases explicit.

Just thought, covering these edge cases is also some kind of documentation for further reference:

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the PR but I think it is unnecessary like you mention. 
Therefore, I'm going to close this PR and related issue

**Pull request closed without merging**
