### PR TITLE
Made CartPoleVectorEnv compliant with #785

### LINKED ISSUE #914: [Bug Report] CartPoleVectorEnv resets one step to early, not following the new VectorEnv API
### Describe the bug

Hi,

according to #785, vector environments are supposed to return the final observation when the current episode is done, instead of immediately returning the first observation of the new episode. `CartPoleVectorEnv` currently does not do this and instead resets its done sub-environments immediately. To fix this issue, the reset of the sub-environments must be delayed, as in `SyncVectorEnv`.

Best,
Tim

### Code example

```shell
from gymnasium.envs.classic_control.cartpole import CartPoleVectorEnv

env = CartPoleVectorEnv(num_envs=1)
env.reset()
while True:
    obs, _, terminated, _, _ = env.step(env.action_space.sample())
    print(obs[0, 0], terminated[0])

# Returns
# 0.0015773153863847256 False
# 0.006231468002155859 False
# 0.014796511112512602 False
# 0.027273956011089992 False
# 0.04366651893222766 False
# 0.06397767074946197 False
# 0.08041100911469909 False
# 0.10077359772242583 False
# -0.011319671757519245 True  <- This value should be from the final observation of the previous
#                                episode (somewhere around 0.1, not -0.01)
```

### System info

_No response_

### Additional context

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

### PR DESCRIPTION
**Pull request by TimSchneider42**
# Description
Made CartPoleVectorEnv compliant with #785 by delaying the reset of done environments until the next step. The current behavior is still following the old VectorEnv API, which means resetting immediately on done and never returning the final observation of an episode.

Fixes #914

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
Thanks @TimSchneider42 for the PR, we didn't have any tests to check the equivalence of the vector and (non-vector) env. 

Making this test, I realised that there were a couple of issues still, could you add the following test to your PR
```python

import gymnasium
import numpy as np


def test_cartpole_vector_equiv():
    env = gymnasium.make("CartPole-v1")
    envs = gymnasium.make_vec("CartPole-v1", num_envs=1)
    
    assert env.action_space == envs.single_action_space
    assert env.observation_space == envs.single_observation_space
    
    
    # reset
    seed = np.random.randint(0, 1000)
    obs, info = env.reset(seed=seed)
    vec_obs, vec_info = envs.reset(seed=seed)
    
    assert obs in env.observation_space
    assert vec_obs in envs.observation_space
    assert np.all(obs == vec_obs[0])
    assert info == vec_info
    
    assert np.all(env.unwrapped.state == envs.unwrapped.state[:, 0])
    
    # step
    for i in range(100):
        action = env.action_space.sample()
        assert np.array([action]) in envs.action_space
    
        obs, reward, term, trunc, info = env.step(action)
        vec_obs, vec_reward, vec_term, vec_trunc, vec_info = envs.step(np.array([action]))
    
        assert obs in env.observation_space
        assert vec_obs in envs.observation_space
        assert np.all(obs == vec_obs[0])
        assert reward == vec_reward
        assert term == vec_term
        assert trunc == vec_trunc
        assert info == vec_info
    
        assert np.all(env.unwrapped.state == envs.unwrapped.state[:, 0])
    
        if term:
            break
    
    obs, info = env.reset()
    # the vector action shouldn't matter as autoreset
    vec_obs, vec_reward, vec_term, vec_trunc, vec_info = envs.step(envs.action_space.sample())
    
    assert obs in env.observation_space
    assert vec_obs in envs.observation_space
    assert np.all(obs == vec_obs[0])
    assert vec_reward == np.array([0])
    assert vec_term == np.array([False])
    assert vec_trunc == np.array([False])
    assert info == vec_info
    
    assert np.all(env.unwrapped.state == envs.unwrapped.state[:, 0])
    
    env.close()
    envs.close()
```

Also, could you merge to main which should solve the CI's issues

**Comment by pseudo-rnd-thoughts** [comment]
@TimSchneider42 You will need to run `pre-commit run --all-files` local to fix the pre-commit issues

**Comment by TimSchneider42** [comment]
Thanks for fixing it! And sorry for all the commits, I am not very experienced with CI and did not know how to run these checks locally.

**Comment by pseudo-rnd-thoughts** [comment]
no worries

**Review by pseudo-rnd-thoughts — APPROVED** [review]

**Pull request merged**
