### PR TITLE
Implementation of Minari callback for `play` 

### PR DESCRIPTION
**Pull request by Markus28**
Implements #202

Still need to check:
- Do reward, terminated, truncated etc. have to have a singleton dimension as in tutorials
- How to handle non-numpy observations, actions
- Are non-flat observations/actions handled correctly by Minari?
- Can we save intermediate results to disk if the replay buffer grows too large?

### CODE REVIEW

**Comment by WillDudley** [comment]
"Can we save intermediate results to disk if the replay buffer grows too large?"

This is a feature I'd like to add to Minari - appending to MinariDatasets in batches. I don't believe this was supported in d3rlpy (which Minari is based off), so it would need to be added.

One potential issue with a replay buffer not fitting into memory is now it's more difficult to sample from earlier transitions (in case you'd want to do some wide-range off-policy learning)

**Comment by pseudo-rnd-thoughts** [comment]
Would it be possible that if we wrap the environment with the minari dataset collector then call `play` on it, this should record all of the actions, observations, etc from the environment?

**Comment by rodrigodelazcano** [comment]
@pseudo-rnd-thoughts that should be the case. We'll have to specify an event to call `minari.create_dataset_from_collector_env()` so that the data can be stored in a permanent location. This can be done with a custom `callback` in `play` and also adding the environment as one of the arguments.

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano Could we not make that call before or after calling `play`. My point is more that I don't think it is necessary to modify `play` to saving the data.

**Comment by pseudo-rnd-thoughts** [comment]
We are going to make this change in minari

**Pull request closed without merging**
