### PR TITLE
[CartPole] add `sutton_barto_reward` to vector and jax

### PR DESCRIPTION
**Pull request by Kallinteris-Andreas**
# Description

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Kallinteris-Andreas** [comment]
Note: the `jax` version of cartpole has a reward function of `1` for non-terminal states and `0` for terminal states.   
https://github.com/Farama-Foundation/Gymnasium/blob/8c8857ecd00fa274d1e90c144319a4a9a97a2dfe/gymnasium/envs/phys2d/cartpole.py#L110-L128

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
Vector update looks good, could you update the jax version in https://github.com/Farama-Foundation/Gymnasium/blob/main/gymnasium/envs/phys2d/cartpole.py 
Thanks

**Comment by Kallinteris-Andreas** [comment]
@pseudo-rnd-thoughts Did you read the previous comment?

**Comment by pseudo-rnd-thoughts** [comment]
Sorry I must have missed it, I would update to reflect the standard verson, i.e., 1 or not terminated

**Pull request merged**
