### PR TITLE
Update vector_envs_tutorial.py

### PR DESCRIPTION
**Pull request by lazybuttrying**
ADD if __name__ == "__main__" to avoid error on multiprocessing

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
https://github.com/Farama-Foundation/Gymnasium/issues/309

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
What is the error that happens without `__name__ == "__main__"`?

**Comment by lazybuttrying** [comment]
I'm sorry for less careful commenting.
Now I did pre-commit run --all-files and committed this time.  

Below issue was triggered at ```gym.vector.make``` and ```gym.vector.AsyncVectorEnv```

I ran on Python 3.10 and my computer is ```21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64```


스크린샷 2023-02-09 오전 11 04 35

**Comment by pseudo-rnd-thoughts** [comment]
@lazybuttrying Could we try to just adding a note to the beginning of the tutorial. I think that most people will just use the jupyter notebook

**Comment by lazybuttrying** [comment]
Actually It happen on jupyter notebook too but I think it is nice idea.
Changing sequence due to the issue makes code as spaghetti.

On this weekend, I will get back the code and add the notice comment on the head of the file.
Also I will upload error screenshot on the jupyter and follow your document instruction carefully.

Thanks for your attention.

**Pull request closed without merging**
