### PR TITLE
Deprecate use of `np.bool_` in tests.

### PR DESCRIPTION
**Pull request by jjshoots**

### CODE REVIEW

**Comment by RedTachyon** [comment]
Why do we want to do this?

**Comment by RedTachyon** [comment]
Wait what? Testing now on numpy 1.23.3 I'm getting e.g.
```python
isinstance(np.bool_(True), bool) == False
```

As far as I remember, the deprecation was that `np.bool` was aliased to `bool` and is now deprecated. `np.bool_` and `bool` are still different.

**Comment by pseudo-rnd-thoughts** [comment]
The numpy docs agree with @RedTachyon 

https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bool_

**Comment by jjshoots** [comment]
Interesting... Probably 2 am disillusionment then. Closing this.

**Pull request closed without merging**
