### PR TITLE
Agilerl tutorials

### PR DESCRIPTION
**Pull request by mikepratt1**
# Description

Adding three AgileRL gymnasium tutorials to the Gymnasium documentation:
- LunarLander with TD3
- Acrobot with PPO
- Cartpole with RainbowDQN

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update (addition of AgileRL tutorials to the docs)

### Screenshots

Please attach before and after screenshots of the change if applicable.
N/A

# Checklist:

- [x ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Kallinteris-Andreas — CHANGES_REQUESTED** [review]
To add some context, these tutorials are a copy of: https://docs.agilerl.com/en/latest/tutorials/gymnasium/index.html

These should be a link, like the "Comet Tutorial", it is bad practice to dual host the tutorials.

**Comment by nicku-a** [comment]
Hey @Kallinteris-Andreas. I'm on the AgileRL team with @mikepratt1. We've previously spoken with @pseudo-rnd-thoughts on Discord about making this PR. We've created similar tutorials for PettingZoo, where we've been very involved in the community, and were encouraged to do the same for Gymnasium.

**Review by nicku-a — APPROVED** [review]

**Comment by RedTachyon** [comment]
Tbh I'm very unsure if we should be putting this kinds of tutorials in the docs. This is more of a tutorial on how to use AgileRL, rather than something specific to Gymnasium, and idk if we have reasons to effectively endorse AgileRL like that.

**Comment by Kallinteris-Andreas** [comment]
I would add that tutorials in the gymnasium documentation site, should be about using gymnasium, not using other libraries, though I would support linking to them like we do with Comet Tutorials.

@pseudo-rnd-thoughts thoughts?

**Comment by nicku-a** [comment]
I understand your concerns. We approached this in the same way we did with the ones we were invited to make for PettingZoo, but I can appreciate wanting to do it differently for Gymnasium. Let us know how is best to proceed!

**Comment by nicku-a** [comment]
Hey @Kallinteris-Andreas @RedTachyon @pseudo-rnd-thoughts how can we proceed?

**Comment by Kallinteris-Andreas** [comment]
Ultimately, it is @pseudo-rnd-thoughts's decision

**Comment by pseudo-rnd-thoughts** [comment]
Apologies for the lack of communication on my part and for not replying on this earlier.
Currently, all of our gymnasium tutorials are about how to use gymnasium exclusively (and where necessary with a critical library, e.g., PyTorch). The comet tutorial is an exception to this that will be removed in the future.

Therefore, as this tutorial is about how to use AgileRL with Gymnasium then it doesn't fit our style currently. 
In the future, if there is a change in the content of our tutorials then we can reconsider. 

Part of our current consideration is we would like to avoid the tutorial section being a hundred tutorials about how to use tool X with gymnasium.
That being said, we are highly appreciative of tutorials for Gymnasium to help users integrate it into different projects
Therefore, we would like to add a third-party tutorial page, like the third-party environment page, for projects to link to their tutorial.

**Pull request closed without merging**
