### PR TITLE
Gymnasium game examples

### PR DESCRIPTION
**Pull request by SteveProXNA**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation only change (no code changed)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
@SteveProXNA Have you intentionally created this PR?

**Comment by SteveProXNA** [comment]
> @SteveProXNA Have you intentionally created this PR?

Yes @pseudo-rnd-thoughts - I have intentionally created this PR as I wanted to contribute to the project by adding an `official` examples package.  I have submitted as Draft PR as I am still in the process of reading all the Contribution guidelines - thanks

**Comment by RedTachyon** [comment]
@SteveProXNA closing this for now, feel free to create a new PR when you have something more concrete. I don't fully understand what you envision this to be, but for larger contributions I recommend making an issue first to check if they're aligned with the direction we have in mind for the library.

**Comment by SteveProXNA** [comment]
Thanks @RedTachyon - I see there is an extensive suite of tests but I my goal was just to create a simple `examples` package in which you could launch any one of the environments seamlessly - almost like an integration test in which a noob developer could easily debug-step through the source code using an environment as the driver.  Pls correct me if I'm wrong but I couldn't seem to see such an option in this source code repo.  Thanks.  PS: I can take your advice a log an `issue` as you suggest if that makes sense

**Pull request closed without merging**
