### PR TITLE
Update train_agent.md

### LINKED ISSUE #28: [Proposal] Tutorials
### Proposal

To encourage the use of Gymnasium and build up the RL community, I would propose that a large range of tutorials are created. 

This is a list of tutorials that could be made

- [ ] Implementation of a custom environment
- [ ] DQN for atari implementation (doesn't need to be fast)
- [ ] Training an agent for the new Phys3d / Phys2d environments (brax) using pytorch or jax
- [ ] Frozenlake training results with different map sizes
- [ ] Gym vectorisation (gym.vector.make)
- [ ] Training agents for the blackjack environment, it has Tuple observation space
- [ ] How to use the action sample masking, with example from Taxi
- [ ] Car racing, comparing agents with continuous and discrete action spaces
- [ ] Training a deep RL agent with pytorch (with the new step API)
- [ ] Using gym make, spec, register and registry
- [ ] Understand the gym spaces
- [ ] Exploring the impact of bipedal walker `hardcore` parameter on agent performance
- [ ] Train an agent with stable-baselines-3
- [ ] Train an agent with tianshou 
- [ ] Using gym for Multi-agent RL
- [ ] Using gym for Offline RL with D4RL
- [ ] How to render an environment
- [ ] How to develop an environment using the gym MDP API
- [ ] Using the gym wrappers and developing custom wrappers
- [ ] visualising your agent with gym.utils.play
- [ ] Understanding the gym environment checker
- [ ] Experimenting with classic control reset options random state bounds

### PR DESCRIPTION
**Pull request by TangLongbin**
# Description

In train_agent.md, the class BlackjackAgent needs env for initialization, but the [demo code](https://gymnasium.farama.org/introduction/train_agent/#training-the-agent) is initialized without env which results in errors. I added the parameters and use 'agent.env' instead of 'env' in the training.

No code for post-processing the training log (such as reward, episode length and training error) visualization. It should be average value rather value of each episode (gym.wrappers.RecordEpisodeStatistics only records this) which is not the same as [figure provided in the doc](https://gymnasium.farama.org/_images/blackjack_training_plots.png). So I add the average value calculation (for later visualization) and the visualization code using matplotlib to help people get the result the expected.

## Type of change

Please delete options that are not relevant.

- [x] Documentation only change (no code changed)

### Screenshots

Please attach before and after screenshots of the change if applicable.

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
@TangLongbin Could you summarise what you are fixing or solving in this PR?

**Comment by TangLongbin** [comment]
> @TangLongbin Could you summarise what you are fixing or solving in this PR?

Sure! I remembered that i added description when pulling the request, but it's gone for some reasons. Sorry for that! I'll explain the modification here:

- In `train_agent.md`, the `class BlackjackAgent` needs `env` for initialization, but the [demo code](https://gymnasium.farama.org/introduction/train_agent/#training-the-agent) is initialized without `env` which results in errors. I added the parameters and use 'agent.env' instead of 'env' in the training.

- No code for post-processing the training log (such as `reward`, `episode length` and `training error`) visualization. It should be average value rather value of each episode (`gym.wrappers.RecordEpisodeStatistics` only records this) which is not the same as [figure provided in the doc](https://gymnasium.farama.org/_images/blackjack_training_plots.png). So I add the average value calculation (for later visualization) and the visualization code using `matplotlib` to help people get the result the expected.

**Review by pseudo-rnd-thoughts — APPROVED** [review]
Apologies for taking a couple of days to respond @TangLongbin 
I've updated the code, I think that `agent.env` is unnecessary and have removed
And the rolling mean code that you added, I used `np.convolve` like in the original tutorial that will compute this more simplify for us

**Comment by TangLongbin** [comment]
> Apologies for taking a couple of days to respond @TangLongbin I've updated the code, I think that `agent.env` is unnecessary and have removed And the rolling mean code that you added, I used `np.convolve` like in the original tutorial that will compute this more simplify for us

THX！

**Pull request merged**
